modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="astrotelemetry"
version="1.0.0"
displayName="Astro Telemetry"
authors="ScienceModder"
description='''
Клиентский научно-исследовательский мод для мониторинга космических и радио-данных.
'''

[[dependencies.astrotelemetry]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.astrotelemetry]]
modId="minecraft"
mandatory=true
versionRange="1.20.1"
ordering="NONE"
side="CLIENT"
